# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=go
runtime: go123

# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=go#runtime_and_app_elements
app_engine_apis: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  login: admin
  secure: always

- url: /.*
  script: auto
  login: admin
  secure: always
