application: s~sauer-pda
version: git-md5-hash
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on
- admin_redirect: on

inbound_services:
- mail
- xmpp_message
- xmpp_presence

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

- url: /_ah/mail/.+
  script: main.application
  login: admin

- url: /_ah/xmpp/presence/available/
  static_files: empty.txt
  upload: empty.txt

- url: /_ah/xmpp/presence/probe/
  static_files: empty.txt
  upload: empty.txt

- url: /_ah/xmpp/presence/unavailable/
  static_files: empty.txt
  upload: empty.txt

- url: /_ah/xmpp/subscription/subscribe/
  static_files: empty.txt
  upload: empty.txt

- url: /_ah/xmpp/subscription/subscribed/
  static_files: empty.txt
  upload: empty.txt

- url: /.*
  script: main.application
  login: admin
  secure: always
