application: s~sauer-pda
version: git-md5-hash
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on
- remote_api: on

inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /_ah/mail/.+
  script: main.py
  login: admin

- url: /.*
  script: main.py
  login: admin
  secure: always
