# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=go
runtime: go123

# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=go#runtime_and_app_elements
app_engine_apis: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  login: admin
  secure: always
  mime_type: image/x-icon

- url: /main\.js
  static_files: static/main.js
  upload: static/main\.js
  login: admin
  secure: always
  mime_type: application/javascript

- url: /main\.css
  static_files: static/main.css
  upload: static/main\.css
  login: admin
  secure: always
  mime_type: text/css

- url: /.*
  script: auto
  login: admin
  secure: always
