application: s~sauer-pda
version: git-md5-hash
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

inbound_services:
- mail

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /_ah/mail/.+
  script: main.application
  login: admin

- url: /.*
  script: main.application
  login: admin
  secure: always
